### ISSUE TITLE
Translations: I can not find these tags in the .po file

### ISSUE THREAD

**Issue by PanuWeb** [espocrm/espocrm#727]
Hello everyone!
These days I was doing an exogenous review of EspoCRM's Spanish translation and I found several problems

1. I am translating from the project in Poeditor.com (as they suggested a few days ago). But I had to review all the terms that the PO file has (more than 2500), because the contributions I made using Pull Request, had not been applied to the Spanish language (at least those of this last year).
Anyway, it helped me to make corrections in many of them and improve the translation.

2. Some labels that can not be translated: this is because the labels are not in the PO file. On the other hand if they can be modified from the tag editor. Attached captures of each case:

* Header of the field list
![0002](https://user-images.githubusercontent.com/110789/33528933-fcb3ee7a-d847-11e7-9a2c-38f12c470bdd.png)

* "Field" tag when adding dynamic logic to a field
![0003](https://user-images.githubusercontent.com/110789/33528934-fcd5692e-d847-11e7-93cd-adacdab635fd.png)

* Default label in the panels, from the design administrator
![0010](https://user-images.githubusercontent.com/110789/33528942-fe201f18-d847-11e7-9e36-ca53927c2348.png)

* User field "IsSuperAdmin"
![0001](https://user-images.githubusercontent.com/110789/33528932-fc91c674-d847-11e7-80b6-0dc6d95f7d60.png)

* "Change Password" label in the user profile actions menu
![0004](https://user-images.githubusercontent.com/110789/33528935-fcf56044-d847-11e7-867f-9e7250053ef2.png)

* "Send by email" action of the article menu in the knowledge base
![0007](https://user-images.githubusercontent.com/110789/33528940-fdc6997a-d847-11e7-8676-03585225102e.png)

* Title in the link to notifications (the image is not visible but it is displayed when there are notifications and you pass the mouse over the link)
![0009](https://user-images.githubusercontent.com/110789/33528941-fdf83886-d847-11e7-8148-f39eb6383440.png)

3. In the case of group accounts, very few labels / fields can be translated (they are not in the PO file). What strikes me is that I already have them in Spanish (?)

* ![0005](https://user-images.githubusercontent.com/110789/33528936-fd194d60-d847-11e7-8ded-490a145411e6.png)
* ![0005b](https://user-images.githubusercontent.com/110789/33528937-fd432e6e-d847-11e7-91a9-23e1e2b77b7d.png)
* ![0006](https://user-images.githubusercontent.com/110789/33528938-fd66232e-d847-11e7-8be5-d91df110a3e4.png)
* ![0006b](https://user-images.githubusercontent.com/110789/33528939-fd87d50a-d847-11e7-9ae1-2a314cb706f8.png)

4. Another problem that I found is that many of the new translations (new fields that are added, for example) are poorly translated or contain the original text in English. This makes it difficult to find new translations. In POEditor, the language es_MX has 98% of the translations but, from what I was seeing, 30% are the same phrases as in English. I do not know why this happens but it would be interesting if the new terms remain blank, this helps us identify them and translate them faster.

Finally I want to thank all the work they do. It is a great CRM. I do not want this thing that I write to bother anyone, it's just my contribution. Let me know when you update the terms in POEditor so I finish the translations.

Regards!

Mauricio.

**Comment by yurikuzn** [comment]
Hi Mauricio,

I've fixed all issues except Group Email Accounts. Can't understand the problem. 

I'm not sure how translation issues occurred in po editor. If it's easier for you to contribute through pull request rather than poeditor, please do. 

Thank you for help.

**Comment by PanuWeb** [comment]
Hello

I have completed the translations but they are still missing: "Send email", "Change Password" and for the design manager "Layout", "Overview" and "new panel".

Regarding group email accounts: I can not find the labels marked with the red arrow in the POEditor.com project and in general, none related to that screen. Anyway, it strikes me that in my installation I have translated them. Maybe because I've been updating since 2.x. I have not tried a clean installation. I am doing something wrong?.

Regarding your last comment: I think it's the best way to use POEditor.com, I think those errors are due to the way in which the contributions of users who come by different means are mixed. At some point, the translations were overwritten with some previous version. In any case it seems better to centralize in POEditor.com and please do not use automatic translation and leave empty fields so you can find and translate more quickly.

One last detail: when you updated the project in POEditor.com I did not receive any notification from the system. I think it is convenient that when you add new translations, use the notification system of POEditor.com [1] to notify of the changes.

Thank you very much

Regards

Mauricio

[1] https://poeditor.com/kb/how-to-send-notifications-to-translators

**Comment by yurikuzn** [comment]
https://poeditor.com/projects/po_edit?order=&filter=&id=58283&id_language=152&search=Send+in+Email

https://poeditor.com/projects/po_edit?order=&filter=&id=58283&id_language=152&search=change+password

It should be translated in dev version. It was a recent bug that items in menu were not translated.

**Comment by yurikuzn** [comment]
https://poeditor.com/projects/po_edit?order=&filter=&id=58283&id_language=152&search=Create+Email+Account

**Comment by yurikuzn** [comment]
"Crear cuenta pesonal" translatation in case of group account should be changed.

**Comment by PanuWeb** [comment]
Ok I found the error: I search for the labels as "fetchSince" that appears in the label editor, but that information is not in the PO file. As it seems that the translations into Spanish that I have were personalized I can not search for them either because in the PO file they are not extacts.

My question now is: how can I restore the customizations that were made in the label manager, so that it takes again the values of the PO file.

**Comment by yurikuzn** [comment]
You can remove custom language files manualy from custom/Espo/Custom/Resources/I18n

**Comment by PanuWeb** [comment]
I did it but they are results. I deleted all the contents of the folder (previous backup), rebuilt, cleaned the cache, deleted the browser data and nothing continue to appear translations that are not those of the PO file :(

**Comment by PanuWeb** [comment]
I have tried again but without results. I comment on my experiment to see if someone detects my error:

I deleted all the files of my installation, just keep the `data` folder. I uploaded the latest stable version of EspoCRM: 4.8.4. I extracted the files. I access the url of Espo and everything normal with the translations that come in the version itself.

Now I'm going to the console. Clone the Espo repository.  I checkout to the tag 4.8.4. I run `npm install` and then `grunt`.

Then I go to POEditor.com and download the `espocrm-es_ES.po` file and save it in `espo_files/build`.

From `espo_files` I run `node lang.js` to create the translations. I compress the folder `es_ES` created and upload it to my server. I extract the folder replacing the original files.

All translations are applied, except some related to the scope **InboundEmail**.

Attached screenshots: (pay attention to the capital letter)

**EspoCRM "Create Group email account" screen**
![0001](https://user-images.githubusercontent.com/110789/33588993-a84e2644-d954-11e7-91bd-7dac344a5286.png)

**POEditor.com correctly translated element**
![0002](https://user-images.githubusercontent.com/110789/33588995-aabfabc8-d954-11e7-91cc-fc4cb8ca286b.png)

**File /application/Espo/Resources/l18n/es_ES/InboundEmail.json**
![0003](https://user-images.githubusercontent.com/110789/33588997-ac4c91ea-d954-11e7-87d6-b5220cc4dede.png)


1. Why does that happen?
2. I am doing something wrong?
3. I wait until version 4.9.0 is published, because the translations are there?

(I clarify that I applied the commands several times: Rebuild + clean cache + refresh browser)

Regards!

**Comment by yurikuzn** [comment]
Need to remove obsolete application/Espo/Modules/Crm/Resources/i18n/es_ES/InboundEmail.json file from repository. 
I will do for all languages.

**Comment by PanuWeb** [comment]
YEEEESSSS!!!! (gestures of raising the arms, standing up and spinning the chair with jumping)

@yurikuzn , you are a genius!

These commits are resolved the issue f70ef6bb14a9bc9b1fa50af594c2e7f85c6aa010 and 5fa591c84f9a20baee9ac237aada2ac4db39df54

Thank you! Thank you! Thank you! for everything they do for the community and for this great CRM.

I hope I have not caught much with this problems.

Thank you very much again!

Regards!

**Comment by yurikuzn** [comment]
Tnx for your contributing. Appreciate.
